# httpproxy.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: jackett
spec:
  virtualhost:
    fqdn: jackett.home.tomcartlabs.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: jackett
          port: 80
