apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jackett
  name: jackett
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9117
  selector:
    app: jackett
status:
  loadBalancer: {}
