# httpproxy.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: rutorrent
spec:
  virtualhost:
    fqdn: rutorrent.home.tomcartlabs.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: rutorrent-tcp
          port: 80
