apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: rutorrent
  labels:
    run: rutorrent
  name: rutorrent-udp
  namespace: default
spec:
  ports:
  - name: port4
    port: 6881
    protocol: UDP
  selector:
    run: rutorrent
  type: LoadBalancer
