apiVersion: apps/v1
kind: Deployment
metadata:
  name: rutorrent
  labels:
    run: rutorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rutorrent
  template:
    metadata:
      labels:
        run: rutorrent
    spec:
      containers:
      - env:
        - name: TZ
          value: America/Chicago
        image: horjulf/rutorrent-autodl
        name: rutorrent
        ports:
        - containerPort: 80
        - containerPort: 5000
        - containerPort: 51413
        - containerPort: 6881
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /downloads
          name: downloads
      volumes:
      - name: config
        nfs:
          server: 192.168.1.11
          path: /volume1/ssd_nfs/k8s/rutorrent
      - name: downloads
        nfs:
          server: 192.168.1.11
          path: /volume1/ssd_nfs/downloads
