# httpproxy.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: sonarr
  
spec:
  virtualhost:
    fqdn: snr.home.tomcartlabs.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: sonarr
          port: 80
