apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sonarr
  name: sonarr
  
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8989
  selector:
    app: sonarr
  type: LoadBalancer
status:
  loadBalancer: {}
